version: 2
  jobs:
    test:
      docker:
        # Node 8 LTS
        - image: circleci/node:carbon
      steps:
        - checkout
        - run: npm install
        - run: npm run lint
        - run: npm test

    docker_push_master:
      docker:
        # Node 8 LTS
        - image: circleci/node:carbon
      steps:
        - checkout
        - run: npm run docker:build
        - run: npm run docker:push

    docker_push_release:
      docker:
        # Node 8 LTS
        - image: circleci/node:carbon
      steps:
        - checkout
        - run: npm run docker:build:release
        - run: npm run docker:push:release

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - npm_publish:
          requires:
            - build
          filters:
            tags:
              only: /.*/ # allow anything because tag syntax is validated as part of validate-release.sh
            branches:
              ignore: /.*/